    ### spring
    spring:
        mvc:
            view:
                prefix: /WEB-INF/views/
                suffix: .jsp
            static-path-pattern: /resource/**

        #hikari pool size
        datasource:
            hikari:
                maximum-pool-size: 10

            ## DB Connection
            url: jdbc:log4jdbc:mariadb://localhost:3306/project
            #driver-class-name: org.mariadb.jdbc.Driver
            driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
            username: root
            password: test123
            #password : ENC(HcGM1fCaENprLeBAqFXStw==)

            mapper-locations: classpath:/mapper/**/*.xml
            jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/project

        ## JPA
        jpa:
            open-in-view: false
            generate-ddl: false
            show-sql: true

        ## Message
        messages:
            basename: messages/main, messages/root
            encoding: UTF-8

    ### server
    server:
        port: 80

        error:
            whitelabel:
                enabled: false

        path: /error

    ## Jasypt
    jasypt:
        encryptor:
            bean: jasyptStringEncryptor